import os

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API")
YOUTUBE_PLAYLIST_ID = "PLzPYp5RV5fmMmjEDgJvtXomiwGbyv_h3I"

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")
SPOTIFY_PLAYLIST_ID = "4PL9KYiriK3kwOjif7JRER"

MAX_RESULTS = 50 
